version: '3'

services:
  server:
    container_name: trials-server
    build: .
    volumes:
      - .:/usr/src/trials
      - /usr/src/trials/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:8000'

  db:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
